# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Tue Sep 15 22:46:22 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1169, 812)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1147, 770))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.groupBox_file = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_file.setGeometry(QtCore.QRect(40, 40, 431, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_file.setFont(font)
        self.groupBox_file.setObjectName(_fromUtf8("groupBox_file"))
        self.lineEdit_address = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_address.setGeometry(QtCore.QRect(120, 90, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_address.setFont(font)
        self.lineEdit_address.setObjectName(_fromUtf8("lineEdit_address"))
        self.pushButton_browse = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_browse.setGeometry(QtCore.QRect(170, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse.setFont(font)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.label = QtGui.QLabel(self.groupBox_file)
        self.label.setGeometry(QtCore.QRect(20, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.groupBox_file)
        self.label_4.setGeometry(QtCore.QRect(40, 150, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_condition1 = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_condition1.setGeometry(QtCore.QRect(120, 150, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_condition1.setFont(font)
        self.lineEdit_condition1.setObjectName(_fromUtf8("lineEdit_condition1"))
        self.groupBox_plot = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_plot.setEnabled(False)
        self.groupBox_plot.setGeometry(QtCore.QRect(490, 40, 621, 651))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_plot.setFont(font)
        self.groupBox_plot.setObjectName(_fromUtf8("groupBox_plot"))
        self.widget = QtGui.QWidget(self.groupBox_plot)
        self.widget.setGeometry(QtCore.QRect(10, 30, 601, 411))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.mplwidget = MatplotlibWidget(self.widget)
        self.mplwidget.setGeometry(QtCore.QRect(290, 200, 16, 16))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.comboBox_x = QtGui.QComboBox(self.groupBox_plot)
        self.comboBox_x.setGeometry(QtCore.QRect(120, 490, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_x.setFont(font)
        self.comboBox_x.setObjectName(_fromUtf8("comboBox_x"))
        self.comboBox_y = QtGui.QComboBox(self.groupBox_plot)
        self.comboBox_y.setGeometry(QtCore.QRect(350, 490, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y.setFont(font)
        self.comboBox_y.setObjectName(_fromUtf8("comboBox_y"))
        self.pushButton_plot = QtGui.QPushButton(self.groupBox_plot)
        self.pushButton_plot.setGeometry(QtCore.QRect(260, 540, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_plot.setFont(font)
        self.pushButton_plot.setObjectName(_fromUtf8("pushButton_plot"))
        self.label_2 = QtGui.QLabel(self.groupBox_plot)
        self.label_2.setGeometry(QtCore.QRect(210, 460, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_plot)
        self.label_3.setGeometry(QtCore.QRect(440, 460, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_plot)
        self.label_5.setGeometry(QtCore.QRect(120, 600, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_condition2 = QtGui.QLineEdit(self.groupBox_plot)
        self.lineEdit_condition2.setGeometry(QtCore.QRect(220, 600, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_condition2.setFont(font)
        self.lineEdit_condition2.setText(_fromUtf8(""))
        self.lineEdit_condition2.setObjectName(_fromUtf8("lineEdit_condition2"))
        self.groupBox_labels = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_labels.setEnabled(False)
        self.groupBox_labels.setGeometry(QtCore.QRect(40, 270, 431, 421))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_labels.setFont(font)
        self.groupBox_labels.setObjectName(_fromUtf8("groupBox_labels"))
        self.label_6 = QtGui.QLabel(self.groupBox_labels)
        self.label_6.setGeometry(QtCore.QRect(80, 40, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_show = QtGui.QPushButton(self.groupBox_labels)
        self.pushButton_show.setGeometry(QtCore.QRect(260, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_show.setFont(font)
        self.pushButton_show.setObjectName(_fromUtf8("pushButton_show"))
        self.textEdit_labels = QtGui.QTextEdit(self.groupBox_labels)
        self.textEdit_labels.setGeometry(QtCore.QRect(50, 100, 351, 311))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit_labels.setFont(font)
        self.textEdit_labels.setObjectName(_fromUtf8("textEdit_labels"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_file.setTitle(_translate("MainWindow", "File", None))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse", None))
        self.label.setText(_translate("MainWindow", "File Address:", None))
        self.label_4.setText(_translate("MainWindow", "Condition:", None))
        self.groupBox_plot.setTitle(_translate("MainWindow", "Plot", None))
        self.pushButton_plot.setText(_translate("MainWindow", "Plot", None))
        self.label_2.setText(_translate("MainWindow", " X-Axis", None))
        self.label_3.setText(_translate("MainWindow", " Y-Axis", None))
        self.label_5.setText(_translate("MainWindow", "Condition:", None))
        self.groupBox_labels.setTitle(_translate("MainWindow", "Labels", None))
        self.label_6.setText(_translate("MainWindow", "Labels Text Box:", None))
        self.pushButton_show.setText(_translate("MainWindow", "Show", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

