# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Wed Feb 03 16:02:33 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1206, 1024)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1184, 991))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_file = QtGui.QGroupBox(self.tab)
        self.groupBox_file.setGeometry(QtCore.QRect(10, 0, 341, 391))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_file.setFont(font)
        self.groupBox_file.setObjectName(_fromUtf8("groupBox_file"))
        self.lineEdit_address = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_address.setGeometry(QtCore.QRect(10, 200, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_address.setFont(font)
        self.lineEdit_address.setObjectName(_fromUtf8("lineEdit_address"))
        self.pushButton_browse = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_browse.setEnabled(False)
        self.pushButton_browse.setGeometry(QtCore.QRect(150, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse.setFont(font)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.label = QtGui.QLabel(self.groupBox_file)
        self.label.setGeometry(QtCore.QRect(10, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.groupBox_file)
        self.label_4.setGeometry(QtCore.QRect(10, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_condition = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_condition.setGeometry(QtCore.QRect(10, 340, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_condition.setFont(font)
        self.lineEdit_condition.setObjectName(_fromUtf8("lineEdit_condition"))
        self.label_10 = QtGui.QLabel(self.groupBox_file)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_divider = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_divider.setGeometry(QtCore.QRect(110, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_divider.setFont(font)
        self.lineEdit_divider.setText(_fromUtf8(""))
        self.lineEdit_divider.setObjectName(_fromUtf8("lineEdit_divider"))
        self.radioButton_qmd = QtGui.QRadioButton(self.groupBox_file)
        self.radioButton_qmd.setGeometry(QtCore.QRect(10, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_qmd.setFont(font)
        self.radioButton_qmd.setChecked(False)
        self.radioButton_qmd.setObjectName(_fromUtf8("radioButton_qmd"))
        self.radioButton_frontpanel = QtGui.QRadioButton(self.groupBox_file)
        self.radioButton_frontpanel.setGeometry(QtCore.QRect(10, 70, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_frontpanel.setFont(font)
        self.radioButton_frontpanel.setObjectName(_fromUtf8("radioButton_frontpanel"))
        self.radioButton_ppms = QtGui.QRadioButton(self.groupBox_file)
        self.radioButton_ppms.setGeometry(QtCore.QRect(140, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ppms.setFont(font)
        self.radioButton_ppms.setChecked(False)
        self.radioButton_ppms.setObjectName(_fromUtf8("radioButton_ppms"))
        self.pushButton_openfile = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_openfile.setEnabled(False)
        self.pushButton_openfile.setGeometry(QtCore.QRect(250, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_openfile.setFont(font)
        self.pushButton_openfile.setObjectName(_fromUtf8("pushButton_openfile"))
        self.label_11 = QtGui.QLabel(self.groupBox_file)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(10, 250, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_recent = QtGui.QComboBox(self.groupBox_file)
        self.comboBox_recent.setEnabled(False)
        self.comboBox_recent.setGeometry(QtCore.QRect(110, 250, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_recent.setFont(font)
        self.comboBox_recent.setObjectName(_fromUtf8("comboBox_recent"))
        self.pushButton_recent = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_recent.setEnabled(False)
        self.pushButton_recent.setGeometry(QtCore.QRect(190, 290, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_recent.setFont(font)
        self.pushButton_recent.setObjectName(_fromUtf8("pushButton_recent"))
        self.radioButton_zbridge = QtGui.QRadioButton(self.groupBox_file)
        self.radioButton_zbridge.setEnabled(True)
        self.radioButton_zbridge.setGeometry(QtCore.QRect(190, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_zbridge.setFont(font)
        self.radioButton_zbridge.setObjectName(_fromUtf8("radioButton_zbridge"))
        self.radioButton_compressor = QtGui.QRadioButton(self.groupBox_file)
        self.radioButton_compressor.setGeometry(QtCore.QRect(220, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_compressor.setFont(font)
        self.radioButton_compressor.setChecked(False)
        self.radioButton_compressor.setObjectName(_fromUtf8("radioButton_compressor"))
        self.groupBox_labels = QtGui.QGroupBox(self.tab)
        self.groupBox_labels.setEnabled(False)
        self.groupBox_labels.setGeometry(QtCore.QRect(10, 400, 341, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_labels.setFont(font)
        self.groupBox_labels.setObjectName(_fromUtf8("groupBox_labels"))
        self.label_6 = QtGui.QLabel(self.groupBox_labels)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_labels = QtGui.QTextEdit(self.groupBox_labels)
        self.textEdit_labels.setGeometry(QtCore.QRect(10, 50, 321, 471))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_labels.setFont(font)
        self.textEdit_labels.setObjectName(_fromUtf8("textEdit_labels"))
        self.groupBox_plot = QtGui.QGroupBox(self.tab)
        self.groupBox_plot.setEnabled(False)
        self.groupBox_plot.setGeometry(QtCore.QRect(360, 0, 791, 931))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_plot.setFont(font)
        self.groupBox_plot.setObjectName(_fromUtf8("groupBox_plot"))
        self.widget = QtGui.QWidget(self.groupBox_plot)
        self.widget.setGeometry(QtCore.QRect(0, 10, 791, 521))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.mplwidget = MatplotlibWidget(self.widget)
        self.mplwidget.setGeometry(QtCore.QRect(290, 200, 16, 16))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.pushButton_change_name = QtGui.QPushButton(self.groupBox_plot)
        self.pushButton_change_name.setEnabled(False)
        self.pushButton_change_name.setGeometry(QtCore.QRect(500, 710, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_change_name.setFont(font)
        self.pushButton_change_name.setObjectName(_fromUtf8("pushButton_change_name"))
        self.label_7 = QtGui.QLabel(self.groupBox_plot)
        self.label_7.setGeometry(QtCore.QRect(430, 600, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_x = QtGui.QLineEdit(self.groupBox_plot)
        self.lineEdit_x.setGeometry(QtCore.QRect(540, 600, 231, 31))
        self.lineEdit_x.setObjectName(_fromUtf8("lineEdit_x"))
        self.label_8 = QtGui.QLabel(self.groupBox_plot)
        self.label_8.setGeometry(QtCore.QRect(430, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_y = QtGui.QLineEdit(self.groupBox_plot)
        self.lineEdit_y.setGeometry(QtCore.QRect(540, 650, 231, 31))
        self.lineEdit_y.setObjectName(_fromUtf8("lineEdit_y"))
        self.label_9 = QtGui.QLabel(self.groupBox_plot)
        self.label_9.setGeometry(QtCore.QRect(430, 550, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_name = QtGui.QLineEdit(self.groupBox_plot)
        self.lineEdit_name.setGeometry(QtCore.QRect(540, 550, 231, 31))
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.pushButton_Plot = QtGui.QPushButton(self.groupBox_plot)
        self.pushButton_Plot.setGeometry(QtCore.QRect(630, 700, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_Plot.setFont(font)
        self.pushButton_Plot.setObjectName(_fromUtf8("pushButton_Plot"))
        self.groupBox_date = QtGui.QGroupBox(self.groupBox_plot)
        self.groupBox_date.setEnabled(False)
        self.groupBox_date.setGeometry(QtCore.QRect(490, 770, 291, 151))
        self.groupBox_date.setObjectName(_fromUtf8("groupBox_date"))
        self.label_18 = QtGui.QLabel(self.groupBox_date)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_minute = QtGui.QLineEdit(self.groupBox_date)
        self.lineEdit_minute.setGeometry(QtCore.QRect(60, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_minute.setFont(font)
        self.lineEdit_minute.setObjectName(_fromUtf8("lineEdit_minute"))
        self.label_19 = QtGui.QLabel(self.groupBox_date)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_date = QtGui.QLineEdit(self.groupBox_date)
        self.lineEdit_date.setGeometry(QtCore.QRect(10, 100, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_date.setFont(font)
        self.lineEdit_date.setObjectName(_fromUtf8("lineEdit_date"))
        self.pushButton_find = QtGui.QPushButton(self.groupBox_date)
        self.pushButton_find.setGeometry(QtCore.QRect(190, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_find.setFont(font)
        self.pushButton_find.setObjectName(_fromUtf8("pushButton_find"))
        self.tabWidget_xy = QtGui.QTabWidget(self.groupBox_plot)
        self.tabWidget_xy.setGeometry(QtCore.QRect(10, 540, 371, 201))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_xy.setFont(font)
        self.tabWidget_xy.setObjectName(_fromUtf8("tabWidget_xy"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(70, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox_x = QtGui.QComboBox(self.tab_3)
        self.comboBox_x.setGeometry(QtCore.QRect(130, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_x.setFont(font)
        self.comboBox_x.setObjectName(_fromUtf8("comboBox_x"))
        self.groupBox_x = QtGui.QGroupBox(self.tab_3)
        self.groupBox_x.setGeometry(QtCore.QRect(10, 50, 341, 111))
        self.groupBox_x.setTitle(_fromUtf8(""))
        self.groupBox_x.setObjectName(_fromUtf8("groupBox_x"))
        self.comboBox_x_2 = QtGui.QComboBox(self.groupBox_x)
        self.comboBox_x_2.setGeometry(QtCore.QRect(120, 40, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_x_2.setFont(font)
        self.comboBox_x_2.setObjectName(_fromUtf8("comboBox_x_2"))
        self.radioButton_x_multiply = QtGui.QRadioButton(self.groupBox_x)
        self.radioButton_x_multiply.setGeometry(QtCore.QRect(100, 10, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_x_multiply.setFont(font)
        self.radioButton_x_multiply.setObjectName(_fromUtf8("radioButton_x_multiply"))
        self.radioButton_x_divide = QtGui.QRadioButton(self.groupBox_x)
        self.radioButton_x_divide.setGeometry(QtCore.QRect(20, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_x_divide.setFont(font)
        self.radioButton_x_divide.setChecked(True)
        self.radioButton_x_divide.setObjectName(_fromUtf8("radioButton_x_divide"))
        self.radioButton_x_plus = QtGui.QRadioButton(self.groupBox_x)
        self.radioButton_x_plus.setGeometry(QtCore.QRect(190, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_x_plus.setFont(font)
        self.radioButton_x_plus.setObjectName(_fromUtf8("radioButton_x_plus"))
        self.radioButton_x_minus = QtGui.QRadioButton(self.groupBox_x)
        self.radioButton_x_minus.setGeometry(QtCore.QRect(260, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_x_minus.setFont(font)
        self.radioButton_x_minus.setObjectName(_fromUtf8("radioButton_x_minus"))
        self.label_12 = QtGui.QLabel(self.groupBox_x)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.checkBox_x_value = QtGui.QCheckBox(self.groupBox_x)
        self.checkBox_x_value.setGeometry(QtCore.QRect(190, 80, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_x_value.setFont(font)
        self.checkBox_x_value.setObjectName(_fromUtf8("checkBox_x_value"))
        self.tabWidget_xy.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox_y = QtGui.QComboBox(self.tab_4)
        self.comboBox_y.setGeometry(QtCore.QRect(130, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y.setFont(font)
        self.comboBox_y.setObjectName(_fromUtf8("comboBox_y"))
        self.groupBox_y = QtGui.QGroupBox(self.tab_4)
        self.groupBox_y.setGeometry(QtCore.QRect(10, 50, 341, 111))
        self.groupBox_y.setTitle(_fromUtf8(""))
        self.groupBox_y.setObjectName(_fromUtf8("groupBox_y"))
        self.comboBox_y_2 = QtGui.QComboBox(self.groupBox_y)
        self.comboBox_y_2.setGeometry(QtCore.QRect(120, 40, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y_2.setFont(font)
        self.comboBox_y_2.setObjectName(_fromUtf8("comboBox_y_2"))
        self.radioButton_y_multiply = QtGui.QRadioButton(self.groupBox_y)
        self.radioButton_y_multiply.setGeometry(QtCore.QRect(100, 10, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_y_multiply.setFont(font)
        self.radioButton_y_multiply.setObjectName(_fromUtf8("radioButton_y_multiply"))
        self.radioButton_y_divide = QtGui.QRadioButton(self.groupBox_y)
        self.radioButton_y_divide.setGeometry(QtCore.QRect(20, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_y_divide.setFont(font)
        self.radioButton_y_divide.setChecked(True)
        self.radioButton_y_divide.setObjectName(_fromUtf8("radioButton_y_divide"))
        self.radioButton_y_plus = QtGui.QRadioButton(self.groupBox_y)
        self.radioButton_y_plus.setGeometry(QtCore.QRect(190, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_y_plus.setFont(font)
        self.radioButton_y_plus.setObjectName(_fromUtf8("radioButton_y_plus"))
        self.radioButton_y_minus = QtGui.QRadioButton(self.groupBox_y)
        self.radioButton_y_minus.setGeometry(QtCore.QRect(260, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_y_minus.setFont(font)
        self.radioButton_y_minus.setObjectName(_fromUtf8("radioButton_y_minus"))
        self.label_13 = QtGui.QLabel(self.groupBox_y)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.checkBox_y_value = QtGui.QCheckBox(self.groupBox_y)
        self.checkBox_y_value.setGeometry(QtCore.QRect(190, 80, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_y_value.setFont(font)
        self.checkBox_y_value.setObjectName(_fromUtf8("checkBox_y_value"))
        self.tabWidget_xy.addTab(self.tab_4, _fromUtf8(""))
        self.groupBox_modify = QtGui.QGroupBox(self.groupBox_plot)
        self.groupBox_modify.setGeometry(QtCore.QRect(10, 750, 461, 171))
        self.groupBox_modify.setObjectName(_fromUtf8("groupBox_modify"))
        self.label_5 = QtGui.QLabel(self.groupBox_modify)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_20 = QtGui.QLabel(self.groupBox_modify)
        self.label_20.setGeometry(QtCore.QRect(230, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_y_min = QtGui.QLineEdit(self.groupBox_modify)
        self.lineEdit_y_min.setGeometry(QtCore.QRect(60, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_y_min.setFont(font)
        self.lineEdit_y_min.setObjectName(_fromUtf8("lineEdit_y_min"))
        self.lineEdit_y_max = QtGui.QLineEdit(self.groupBox_modify)
        self.lineEdit_y_max.setGeometry(QtCore.QRect(290, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_y_max.setFont(font)
        self.lineEdit_y_max.setObjectName(_fromUtf8("lineEdit_y_max"))
        self.label_21 = QtGui.QLabel(self.groupBox_modify)
        self.label_21.setGeometry(QtCore.QRect(10, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_modify)
        self.label_22.setGeometry(QtCore.QRect(230, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_x_min = QtGui.QLineEdit(self.groupBox_modify)
        self.lineEdit_x_min.setGeometry(QtCore.QRect(60, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_x_min.setFont(font)
        self.lineEdit_x_min.setObjectName(_fromUtf8("lineEdit_x_min"))
        self.lineEdit_x_max = QtGui.QLineEdit(self.groupBox_modify)
        self.lineEdit_x_max.setGeometry(QtCore.QRect(290, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_x_max.setFont(font)
        self.lineEdit_x_max.setObjectName(_fromUtf8("lineEdit_x_max"))
        self.pushButton_modify = QtGui.QPushButton(self.groupBox_modify)
        self.pushButton_modify.setGeometry(QtCore.QRect(120, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_modify.setFont(font)
        self.pushButton_modify.setObjectName(_fromUtf8("pushButton_modify"))
        self.pushButton_return = QtGui.QPushButton(self.groupBox_modify)
        self.pushButton_return.setGeometry(QtCore.QRect(270, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_return.setFont(font)
        self.pushButton_return.setObjectName(_fromUtf8("pushButton_return"))
        self.label_ymin = QtGui.QLabel(self.groupBox_modify)
        self.label_ymin.setGeometry(QtCore.QRect(140, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ymin.setFont(font)
        self.label_ymin.setText(_fromUtf8(""))
        self.label_ymin.setObjectName(_fromUtf8("label_ymin"))
        self.label_ymax = QtGui.QLabel(self.groupBox_modify)
        self.label_ymax.setGeometry(QtCore.QRect(370, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_ymax.setFont(font)
        self.label_ymax.setText(_fromUtf8(""))
        self.label_ymax.setObjectName(_fromUtf8("label_ymax"))
        self.label_xmax = QtGui.QLabel(self.groupBox_modify)
        self.label_xmax.setGeometry(QtCore.QRect(370, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_xmax.setFont(font)
        self.label_xmax.setText(_fromUtf8(""))
        self.label_xmax.setObjectName(_fromUtf8("label_xmax"))
        self.label_xmin = QtGui.QLabel(self.groupBox_modify)
        self.label_xmin.setGeometry(QtCore.QRect(140, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_xmin.setFont(font)
        self.label_xmin.setText(_fromUtf8(""))
        self.label_xmin.setObjectName(_fromUtf8("label_xmin"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.widget_first_step = QtGui.QWidget(self.groupBox_3)
        self.widget_first_step.setGeometry(QtCore.QRect(230, 0, 931, 471))
        self.widget_first_step.setObjectName(_fromUtf8("widget_first_step"))
        self.mplwidget_first_step = MatplotlibWidget(self.widget_first_step)
        self.mplwidget_first_step.setGeometry(QtCore.QRect(290, 200, 16, 16))
        self.mplwidget_first_step.setObjectName(_fromUtf8("mplwidget_first_step"))
        self.comboBox_y_first_step = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_y_first_step.setGeometry(QtCore.QRect(20, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y_first_step.setFont(font)
        self.comboBox_y_first_step.setObjectName(_fromUtf8("comboBox_y_first_step"))
        self.pushButton_plot_first_step = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_plot_first_step.setEnabled(False)
        self.pushButton_plot_first_step.setGeometry(QtCore.QRect(130, 370, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_plot_first_step.setFont(font)
        self.pushButton_plot_first_step.setObjectName(_fromUtf8("pushButton_plot_first_step"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setEnabled(False)
        self.label_14.setGeometry(QtCore.QRect(160, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.groupBox_first = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_first.setEnabled(False)
        self.groupBox_first.setGeometry(QtCore.QRect(10, 140, 221, 211))
        self.groupBox_first.setTitle(_fromUtf8(""))
        self.groupBox_first.setObjectName(_fromUtf8("groupBox_first"))
        self.comboBox_first = QtGui.QComboBox(self.groupBox_first)
        self.comboBox_first.setGeometry(QtCore.QRect(10, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_first.setFont(font)
        self.comboBox_first.setObjectName(_fromUtf8("comboBox_first"))
        self.radioButton_first_multiply = QtGui.QRadioButton(self.groupBox_first)
        self.radioButton_first_multiply.setGeometry(QtCore.QRect(120, 10, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_first_multiply.setFont(font)
        self.radioButton_first_multiply.setObjectName(_fromUtf8("radioButton_first_multiply"))
        self.radioButton_first_divide = QtGui.QRadioButton(self.groupBox_first)
        self.radioButton_first_divide.setGeometry(QtCore.QRect(30, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_first_divide.setFont(font)
        self.radioButton_first_divide.setChecked(True)
        self.radioButton_first_divide.setObjectName(_fromUtf8("radioButton_first_divide"))
        self.radioButton_first_plus = QtGui.QRadioButton(self.groupBox_first)
        self.radioButton_first_plus.setGeometry(QtCore.QRect(30, 50, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_first_plus.setFont(font)
        self.radioButton_first_plus.setObjectName(_fromUtf8("radioButton_first_plus"))
        self.radioButton_first_minus = QtGui.QRadioButton(self.groupBox_first)
        self.radioButton_first_minus.setGeometry(QtCore.QRect(120, 50, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_first_minus.setFont(font)
        self.radioButton_first_minus.setObjectName(_fromUtf8("radioButton_first_minus"))
        self.label_16 = QtGui.QLabel(self.groupBox_first)
        self.label_16.setGeometry(QtCore.QRect(100, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.checkBox_first = QtGui.QCheckBox(self.groupBox_first)
        self.checkBox_first.setGeometry(QtCore.QRect(80, 180, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_first.setFont(font)
        self.checkBox_first.setObjectName(_fromUtf8("checkBox_first"))
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.widget_second_step = QtGui.QWidget(self.groupBox_4)
        self.widget_second_step.setGeometry(QtCore.QRect(230, 0, 931, 471))
        self.widget_second_step.setObjectName(_fromUtf8("widget_second_step"))
        self.mplwidget_second_step = MatplotlibWidget(self.widget_second_step)
        self.mplwidget_second_step.setGeometry(QtCore.QRect(290, 200, 16, 16))
        self.mplwidget_second_step.setObjectName(_fromUtf8("mplwidget_second_step"))
        self.comboBox_y_second_step = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_y_second_step.setGeometry(QtCore.QRect(20, 90, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y_second_step.setFont(font)
        self.comboBox_y_second_step.setObjectName(_fromUtf8("comboBox_y_second_step"))
        self.pushButton_plot_second_step = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_plot_second_step.setEnabled(False)
        self.pushButton_plot_second_step.setGeometry(QtCore.QRect(130, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_plot_second_step.setFont(font)
        self.pushButton_plot_second_step.setObjectName(_fromUtf8("pushButton_plot_second_step"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setEnabled(False)
        self.label_15.setGeometry(QtCore.QRect(160, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.groupBox_second = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_second.setEnabled(False)
        self.groupBox_second.setGeometry(QtCore.QRect(10, 150, 221, 211))
        self.groupBox_second.setTitle(_fromUtf8(""))
        self.groupBox_second.setObjectName(_fromUtf8("groupBox_second"))
        self.comboBox_second = QtGui.QComboBox(self.groupBox_second)
        self.comboBox_second.setGeometry(QtCore.QRect(10, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_second.setFont(font)
        self.comboBox_second.setObjectName(_fromUtf8("comboBox_second"))
        self.radioButton_second_multiply = QtGui.QRadioButton(self.groupBox_second)
        self.radioButton_second_multiply.setGeometry(QtCore.QRect(120, 10, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_second_multiply.setFont(font)
        self.radioButton_second_multiply.setObjectName(_fromUtf8("radioButton_second_multiply"))
        self.radioButton_second_divide = QtGui.QRadioButton(self.groupBox_second)
        self.radioButton_second_divide.setGeometry(QtCore.QRect(30, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_second_divide.setFont(font)
        self.radioButton_second_divide.setChecked(True)
        self.radioButton_second_divide.setObjectName(_fromUtf8("radioButton_second_divide"))
        self.radioButton_second_plus = QtGui.QRadioButton(self.groupBox_second)
        self.radioButton_second_plus.setGeometry(QtCore.QRect(30, 50, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_second_plus.setFont(font)
        self.radioButton_second_plus.setObjectName(_fromUtf8("radioButton_second_plus"))
        self.radioButton_second_minus = QtGui.QRadioButton(self.groupBox_second)
        self.radioButton_second_minus.setGeometry(QtCore.QRect(120, 50, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_second_minus.setFont(font)
        self.radioButton_second_minus.setObjectName(_fromUtf8("radioButton_second_minus"))
        self.label_17 = QtGui.QLabel(self.groupBox_second)
        self.label_17.setGeometry(QtCore.QRect(100, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.checkBox_second = QtGui.QCheckBox(self.groupBox_second)
        self.checkBox_second.setGeometry(QtCore.QRect(80, 180, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_second.setFont(font)
        self.checkBox_second.setObjectName(_fromUtf8("checkBox_second"))
        self.verticalLayout.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_xy.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_file.setTitle(_translate("MainWindow", "File", None))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse", None))
        self.label.setText(_translate("MainWindow", "File Address:", None))
        self.label_4.setText(_translate("MainWindow", "Condition:", None))
        self.lineEdit_condition.setText(_translate("MainWindow", "Please choose your csv file type", None))
        self.label_10.setText(_translate("MainWindow", "Data Divider:", None))
        self.radioButton_qmd.setText(_translate("MainWindow", "QMDLAB File", None))
        self.radioButton_frontpanel.setText(_translate("MainWindow", "FrontPanel Data File", None))
        self.radioButton_ppms.setText(_translate("MainWindow", "PPMS", None))
        self.pushButton_openfile.setText(_translate("MainWindow", "Open File", None))
        self.label_11.setText(_translate("MainWindow", "Recent open:", None))
        self.pushButton_recent.setText(_translate("MainWindow", "Open Recent File", None))
        self.radioButton_zbridge.setText(_translate("MainWindow", "zBridge Data File", None))
        self.radioButton_compressor.setText(_translate("MainWindow", "Compressor", None))
        self.groupBox_labels.setTitle(_translate("MainWindow", "Labels", None))
        self.label_6.setText(_translate("MainWindow", "Labels Text Box:", None))
        self.groupBox_plot.setTitle(_translate("MainWindow", "Plot", None))
        self.pushButton_change_name.setText(_translate("MainWindow", "Save Name", None))
        self.label_7.setText(_translate("MainWindow", " X-Axis Name:", None))
        self.label_8.setText(_translate("MainWindow", " Y-Axis Name:", None))
        self.label_9.setText(_translate("MainWindow", " Plot Name:", None))
        self.pushButton_Plot.setText(_translate("MainWindow", "Plot", None))
        self.groupBox_date.setTitle(_translate("MainWindow", "Find Date", None))
        self.label_18.setText(_translate("MainWindow", "Time:", None))
        self.label_19.setText(_translate("MainWindow", "Date & Time:", None))
        self.pushButton_find.setText(_translate("MainWindow", "Find", None))
        self.label_2.setText(_translate("MainWindow", " X-Axis", None))
        self.radioButton_x_multiply.setText(_translate("MainWindow", "Multiply", None))
        self.radioButton_x_divide.setText(_translate("MainWindow", "Divide", None))
        self.radioButton_x_plus.setText(_translate("MainWindow", "Plus", None))
        self.radioButton_x_minus.setText(_translate("MainWindow", "Minus", None))
        self.label_12.setText(_translate("MainWindow", "Second  X-Axis", None))
        self.checkBox_x_value.setText(_translate("MainWindow", "Absolute Value", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_3), _translate("MainWindow", "X-Axis", None))
        self.label_3.setText(_translate("MainWindow", " Y-Axis", None))
        self.radioButton_y_multiply.setText(_translate("MainWindow", "Multiply", None))
        self.radioButton_y_divide.setText(_translate("MainWindow", "Divide", None))
        self.radioButton_y_plus.setText(_translate("MainWindow", "Plus", None))
        self.radioButton_y_minus.setText(_translate("MainWindow", "Minus", None))
        self.label_13.setText(_translate("MainWindow", "Second  Y-Axis", None))
        self.checkBox_y_value.setText(_translate("MainWindow", "Absolute Value", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_4), _translate("MainWindow", "Y-Axis", None))
        self.groupBox_modify.setTitle(_translate("MainWindow", "Modify Range", None))
        self.label_5.setText(_translate("MainWindow", "Y-Min:", None))
        self.label_20.setText(_translate("MainWindow", " Y-Max:", None))
        self.label_21.setText(_translate("MainWindow", "X-Min:", None))
        self.label_22.setText(_translate("MainWindow", " X-Max:", None))
        self.pushButton_modify.setText(_translate("MainWindow", "Modify", None))
        self.pushButton_return.setText(_translate("MainWindow", "Return", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Regular Plotting", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "First Step Plotting", None))
        self.pushButton_plot_first_step.setText(_translate("MainWindow", "Plot", None))
        self.label_14.setText(_translate("MainWindow", " Y-Axis", None))
        self.radioButton_first_multiply.setText(_translate("MainWindow", "Multiply", None))
        self.radioButton_first_divide.setText(_translate("MainWindow", "Divide", None))
        self.radioButton_first_plus.setText(_translate("MainWindow", "Plus", None))
        self.radioButton_first_minus.setText(_translate("MainWindow", "Minus", None))
        self.label_16.setText(_translate("MainWindow", "Second  Y-Axis", None))
        self.checkBox_first.setText(_translate("MainWindow", "Absolute Value", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Second Step Plotting", None))
        self.pushButton_plot_second_step.setText(_translate("MainWindow", "Plot", None))
        self.label_15.setText(_translate("MainWindow", " Y-Axis", None))
        self.radioButton_second_multiply.setText(_translate("MainWindow", "Multiply", None))
        self.radioButton_second_divide.setText(_translate("MainWindow", "Divide", None))
        self.radioButton_second_plus.setText(_translate("MainWindow", "Plus", None))
        self.radioButton_second_minus.setText(_translate("MainWindow", "Minus", None))
        self.label_17.setText(_translate("MainWindow", "Second  Y-Axis", None))
        self.checkBox_second.setText(_translate("MainWindow", "Absolute Value", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Step Plotting", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

