# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Fri Mar 10 14:46:58 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1842, 925)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1820, 892))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_file = QtGui.QGroupBox(self.tab)
        self.groupBox_file.setGeometry(QtCore.QRect(10, 0, 331, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_file.setFont(font)
        self.groupBox_file.setObjectName(_fromUtf8("groupBox_file"))
        self.lineEdit_address = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_address.setGeometry(QtCore.QRect(10, 40, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_address.setFont(font)
        self.lineEdit_address.setObjectName(_fromUtf8("lineEdit_address"))
        self.pushButton_browse = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_browse.setEnabled(False)
        self.pushButton_browse.setGeometry(QtCore.QRect(140, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse.setFont(font)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.label = QtGui.QLabel(self.groupBox_file)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_open = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_open.setEnabled(False)
        self.pushButton_open.setGeometry(QtCore.QRect(250, 90, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setObjectName(_fromUtf8("pushButton_open"))
        self.groupBox_plot = QtGui.QGroupBox(self.tab)
        self.groupBox_plot.setEnabled(True)
        self.groupBox_plot.setGeometry(QtCore.QRect(350, 0, 1441, 841))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_plot.setFont(font)
        self.groupBox_plot.setObjectName(_fromUtf8("groupBox_plot"))
        self.widget = QtGui.QWidget(self.groupBox_plot)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(0, 10, 1441, 831))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.mplwidget = MatplotlibWidget(self.widget)
        self.mplwidget.setEnabled(True)
        self.mplwidget.setGeometry(QtCore.QRect(290, 200, 16, 16))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.tabWidget_xy = QtGui.QTabWidget(self.tab)
        self.tabWidget_xy.setGeometry(QtCore.QRect(10, 150, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_xy.setFont(font)
        self.tabWidget_xy.setObjectName(_fromUtf8("tabWidget_xy"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox_x = QtGui.QComboBox(self.tab_3)
        self.comboBox_x.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_x.setFont(font)
        self.comboBox_x.setObjectName(_fromUtf8("comboBox_x"))
        self.tabWidget_xy.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_3 = QtGui.QLabel(self.tab_4)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboBox_y1 = QtGui.QComboBox(self.tab_4)
        self.comboBox_y1.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y1.setFont(font)
        self.comboBox_y1.setObjectName(_fromUtf8("comboBox_y1"))
        self.comboBox_color_y1 = QtGui.QComboBox(self.tab_4)
        self.comboBox_color_y1.setGeometry(QtCore.QRect(240, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_color_y1.setFont(font)
        self.comboBox_color_y1.setObjectName(_fromUtf8("comboBox_color_y1"))
        self.comboBox_color_y1.addItem(_fromUtf8(""))
        self.comboBox_color_y1.addItem(_fromUtf8(""))
        self.comboBox_color_y1.addItem(_fromUtf8(""))
        self.comboBox_color_y1.addItem(_fromUtf8(""))
        self.comboBox_color_y1.addItem(_fromUtf8(""))
        self.comboBox_color_y1.addItem(_fromUtf8(""))
        self.tabWidget_xy.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.label_24 = QtGui.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(0, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.comboBox_y2 = QtGui.QComboBox(self.tab_5)
        self.comboBox_y2.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y2.setFont(font)
        self.comboBox_y2.setObjectName(_fromUtf8("comboBox_y2"))
        self.comboBox_color_y2 = QtGui.QComboBox(self.tab_5)
        self.comboBox_color_y2.setGeometry(QtCore.QRect(240, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_color_y2.setFont(font)
        self.comboBox_color_y2.setObjectName(_fromUtf8("comboBox_color_y2"))
        self.comboBox_color_y2.addItem(_fromUtf8(""))
        self.comboBox_color_y2.addItem(_fromUtf8(""))
        self.comboBox_color_y2.addItem(_fromUtf8(""))
        self.comboBox_color_y2.addItem(_fromUtf8(""))
        self.comboBox_color_y2.addItem(_fromUtf8(""))
        self.comboBox_color_y2.addItem(_fromUtf8(""))
        self.tabWidget_xy.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.label_25 = QtGui.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(0, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.comboBox_y3 = QtGui.QComboBox(self.tab_6)
        self.comboBox_y3.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y3.setFont(font)
        self.comboBox_y3.setObjectName(_fromUtf8("comboBox_y3"))
        self.comboBox_color_y3 = QtGui.QComboBox(self.tab_6)
        self.comboBox_color_y3.setGeometry(QtCore.QRect(240, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_color_y3.setFont(font)
        self.comboBox_color_y3.setObjectName(_fromUtf8("comboBox_color_y3"))
        self.comboBox_color_y3.addItem(_fromUtf8(""))
        self.comboBox_color_y3.addItem(_fromUtf8(""))
        self.comboBox_color_y3.addItem(_fromUtf8(""))
        self.comboBox_color_y3.addItem(_fromUtf8(""))
        self.comboBox_color_y3.addItem(_fromUtf8(""))
        self.comboBox_color_y3.addItem(_fromUtf8(""))
        self.tabWidget_xy.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.label_26 = QtGui.QLabel(self.tab_7)
        self.label_26.setGeometry(QtCore.QRect(0, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.comboBox_y4 = QtGui.QComboBox(self.tab_7)
        self.comboBox_y4.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y4.setFont(font)
        self.comboBox_y4.setObjectName(_fromUtf8("comboBox_y4"))
        self.comboBox_color_y4 = QtGui.QComboBox(self.tab_7)
        self.comboBox_color_y4.setGeometry(QtCore.QRect(240, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_color_y4.setFont(font)
        self.comboBox_color_y4.setObjectName(_fromUtf8("comboBox_color_y4"))
        self.comboBox_color_y4.addItem(_fromUtf8(""))
        self.comboBox_color_y4.addItem(_fromUtf8(""))
        self.comboBox_color_y4.addItem(_fromUtf8(""))
        self.comboBox_color_y4.addItem(_fromUtf8(""))
        self.comboBox_color_y4.addItem(_fromUtf8(""))
        self.comboBox_color_y4.addItem(_fromUtf8(""))
        self.tabWidget_xy.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.label_27 = QtGui.QLabel(self.tab_8)
        self.label_27.setGeometry(QtCore.QRect(0, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.comboBox_y5 = QtGui.QComboBox(self.tab_8)
        self.comboBox_y5.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y5.setFont(font)
        self.comboBox_y5.setObjectName(_fromUtf8("comboBox_y5"))
        self.comboBox_color_y5 = QtGui.QComboBox(self.tab_8)
        self.comboBox_color_y5.setGeometry(QtCore.QRect(240, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_color_y5.setFont(font)
        self.comboBox_color_y5.setObjectName(_fromUtf8("comboBox_color_y5"))
        self.comboBox_color_y5.addItem(_fromUtf8(""))
        self.comboBox_color_y5.addItem(_fromUtf8(""))
        self.comboBox_color_y5.addItem(_fromUtf8(""))
        self.comboBox_color_y5.addItem(_fromUtf8(""))
        self.comboBox_color_y5.addItem(_fromUtf8(""))
        self.comboBox_color_y5.addItem(_fromUtf8(""))
        self.tabWidget_xy.addTab(self.tab_8, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.comboBox_y6 = QtGui.QComboBox(self.tab_9)
        self.comboBox_y6.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y6.setFont(font)
        self.comboBox_y6.setObjectName(_fromUtf8("comboBox_y6"))
        self.label_28 = QtGui.QLabel(self.tab_9)
        self.label_28.setGeometry(QtCore.QRect(0, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.comboBox_color_y6 = QtGui.QComboBox(self.tab_9)
        self.comboBox_color_y6.setGeometry(QtCore.QRect(240, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_color_y6.setFont(font)
        self.comboBox_color_y6.setObjectName(_fromUtf8("comboBox_color_y6"))
        self.comboBox_color_y6.addItem(_fromUtf8(""))
        self.comboBox_color_y6.addItem(_fromUtf8(""))
        self.comboBox_color_y6.addItem(_fromUtf8(""))
        self.comboBox_color_y6.addItem(_fromUtf8(""))
        self.comboBox_color_y6.addItem(_fromUtf8(""))
        self.tabWidget_xy.addTab(self.tab_9, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 330, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButton_Next = QtGui.QPushButton(self.groupBox)
        self.pushButton_Next.setEnabled(False)
        self.pushButton_Next.setGeometry(QtCore.QRect(210, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Next.setFont(font)
        self.pushButton_Next.setObjectName(_fromUtf8("pushButton_Next"))
        self.pushButton_Plot = QtGui.QPushButton(self.groupBox)
        self.pushButton_Plot.setEnabled(False)
        self.pushButton_Plot.setGeometry(QtCore.QRect(130, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Plot.setFont(font)
        self.pushButton_Plot.setObjectName(_fromUtf8("pushButton_Plot"))
        self.pushButton_Previous = QtGui.QPushButton(self.groupBox)
        self.pushButton_Previous.setEnabled(False)
        self.pushButton_Previous.setGeometry(QtCore.QRect(60, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Previous.setFont(font)
        self.pushButton_Previous.setObjectName(_fromUtf8("pushButton_Previous"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 331, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_condition = QtGui.QLabel(self.groupBox_2)
        self.label_condition.setGeometry(QtCore.QRect(10, 20, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_condition.setFont(font)
        self.label_condition.setObjectName(_fromUtf8("label_condition"))
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 410, 331, 431))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_12 = QtGui.QWidget()
        self.tab_12.setObjectName(_fromUtf8("tab_12"))
        self.textEdit_labels = QtGui.QTextEdit(self.tab_12)
        self.textEdit_labels.setGeometry(QtCore.QRect(10, 10, 301, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_labels.setFont(font)
        self.textEdit_labels.setObjectName(_fromUtf8("textEdit_labels"))
        self.tabWidget_2.addTab(self.tab_12, _fromUtf8(""))
        self.tab_91 = QtGui.QWidget()
        self.tab_91.setObjectName(_fromUtf8("tab_91"))
        self.lineEdit_name = QtGui.QLineEdit(self.tab_91)
        self.lineEdit_name.setGeometry(QtCore.QRect(20, 40, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.pushButton_change_name = QtGui.QPushButton(self.tab_91)
        self.pushButton_change_name.setEnabled(False)
        self.pushButton_change_name.setGeometry(QtCore.QRect(130, 230, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_change_name.setFont(font)
        self.pushButton_change_name.setObjectName(_fromUtf8("pushButton_change_name"))
        self.label_7 = QtGui.QLabel(self.tab_91)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_y = QtGui.QLineEdit(self.tab_91)
        self.lineEdit_y.setGeometry(QtCore.QRect(20, 180, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_y.setFont(font)
        self.lineEdit_y.setObjectName(_fromUtf8("lineEdit_y"))
        self.lineEdit_x = QtGui.QLineEdit(self.tab_91)
        self.lineEdit_x.setGeometry(QtCore.QRect(20, 110, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_x.setFont(font)
        self.lineEdit_x.setObjectName(_fromUtf8("lineEdit_x"))
        self.label_8 = QtGui.QLabel(self.tab_91)
        self.label_8.setGeometry(QtCore.QRect(20, 150, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab_91)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget_2.addTab(self.tab_91, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.label_21 = QtGui.QLabel(self.tab_10)
        self.label_21.setGeometry(QtCore.QRect(30, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_y_range = QtGui.QLineEdit(self.tab_10)
        self.lineEdit_y_range.setGeometry(QtCore.QRect(30, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_y_range.setFont(font)
        self.lineEdit_y_range.setText(_fromUtf8(""))
        self.lineEdit_y_range.setObjectName(_fromUtf8("lineEdit_y_range"))
        self.label_5 = QtGui.QLabel(self.tab_10)
        self.label_5.setGeometry(QtCore.QRect(30, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_x_range = QtGui.QLineEdit(self.tab_10)
        self.lineEdit_x_range.setGeometry(QtCore.QRect(30, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_x_range.setFont(font)
        self.lineEdit_x_range.setText(_fromUtf8(""))
        self.lineEdit_x_range.setObjectName(_fromUtf8("lineEdit_x_range"))
        self.pushButton_return = QtGui.QPushButton(self.tab_10)
        self.pushButton_return.setGeometry(QtCore.QRect(190, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_return.setFont(font)
        self.pushButton_return.setObjectName(_fromUtf8("pushButton_return"))
        self.pushButton_modify = QtGui.QPushButton(self.tab_10)
        self.pushButton_modify.setGeometry(QtCore.QRect(70, 180, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_modify.setFont(font)
        self.pushButton_modify.setObjectName(_fromUtf8("pushButton_modify"))
        self.checkBox_logx = QtGui.QCheckBox(self.tab_10)
        self.checkBox_logx.setGeometry(QtCore.QRect(190, 50, 121, 31))
        self.checkBox_logx.setObjectName(_fromUtf8("checkBox_logx"))
        self.checkBox_logy = QtGui.QCheckBox(self.tab_10)
        self.checkBox_logy.setGeometry(QtCore.QRect(190, 120, 121, 31))
        self.checkBox_logy.setObjectName(_fromUtf8("checkBox_logy"))
        self.tabWidget_2.addTab(self.tab_10, _fromUtf8(""))
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName(_fromUtf8("tab_11"))
        self.label_18 = QtGui.QLabel(self.tab_11)
        self.label_18.setGeometry(QtCore.QRect(50, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.pushButton_find = QtGui.QPushButton(self.tab_11)
        self.pushButton_find.setGeometry(QtCore.QRect(120, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_find.setFont(font)
        self.pushButton_find.setObjectName(_fromUtf8("pushButton_find"))
        self.label_19 = QtGui.QLabel(self.tab_11)
        self.label_19.setGeometry(QtCore.QRect(50, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_minute = QtGui.QLineEdit(self.tab_11)
        self.lineEdit_minute.setGeometry(QtCore.QRect(110, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_minute.setFont(font)
        self.lineEdit_minute.setObjectName(_fromUtf8("lineEdit_minute"))
        self.label_date = QtGui.QLabel(self.tab_11)
        self.label_date.setGeometry(QtCore.QRect(50, 160, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_date.setFont(font)
        self.label_date.setText(_fromUtf8(""))
        self.label_date.setObjectName(_fromUtf8("label_date"))
        self.tabWidget_2.addTab(self.tab_11, _fromUtf8(""))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_xy.setCurrentIndex(0)
        self.comboBox_color_y2.setCurrentIndex(1)
        self.comboBox_color_y3.setCurrentIndex(2)
        self.comboBox_color_y4.setCurrentIndex(3)
        self.comboBox_color_y5.setCurrentIndex(4)
        self.comboBox_color_y6.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_file.setTitle(_translate("MainWindow", "File", None))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse", None))
        self.label.setText(_translate("MainWindow", "Directory:", None))
        self.pushButton_open.setText(_translate("MainWindow", "Open", None))
        self.groupBox_plot.setTitle(_translate("MainWindow", "Plot", None))
        self.label_2.setText(_translate("MainWindow", " X:", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_3), _translate("MainWindow", "X", None))
        self.label_3.setText(_translate("MainWindow", " Y1:", None))
        self.comboBox_color_y1.setItemText(0, _translate("MainWindow", "Blue", None))
        self.comboBox_color_y1.setItemText(1, _translate("MainWindow", "Green", None))
        self.comboBox_color_y1.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox_color_y1.setItemText(3, _translate("MainWindow", "Yellow", None))
        self.comboBox_color_y1.setItemText(4, _translate("MainWindow", "Black", None))
        self.comboBox_color_y1.setItemText(5, _translate("MainWindow", "Magenta", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_4), _translate("MainWindow", "Y1", None))
        self.label_24.setText(_translate("MainWindow", " Y2:", None))
        self.comboBox_color_y2.setItemText(0, _translate("MainWindow", "Blue", None))
        self.comboBox_color_y2.setItemText(1, _translate("MainWindow", "Green", None))
        self.comboBox_color_y2.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox_color_y2.setItemText(3, _translate("MainWindow", "Yellow", None))
        self.comboBox_color_y2.setItemText(4, _translate("MainWindow", "Black", None))
        self.comboBox_color_y2.setItemText(5, _translate("MainWindow", "Magenta", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_5), _translate("MainWindow", "Y2", None))
        self.label_25.setText(_translate("MainWindow", " Y3:", None))
        self.comboBox_color_y3.setItemText(0, _translate("MainWindow", "Blue", None))
        self.comboBox_color_y3.setItemText(1, _translate("MainWindow", "Green", None))
        self.comboBox_color_y3.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox_color_y3.setItemText(3, _translate("MainWindow", "Yellow", None))
        self.comboBox_color_y3.setItemText(4, _translate("MainWindow", "Black", None))
        self.comboBox_color_y3.setItemText(5, _translate("MainWindow", "Magenta", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_6), _translate("MainWindow", "Y3", None))
        self.label_26.setText(_translate("MainWindow", " Y4:", None))
        self.comboBox_color_y4.setItemText(0, _translate("MainWindow", "Blue", None))
        self.comboBox_color_y4.setItemText(1, _translate("MainWindow", "Green", None))
        self.comboBox_color_y4.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox_color_y4.setItemText(3, _translate("MainWindow", "Yellow", None))
        self.comboBox_color_y4.setItemText(4, _translate("MainWindow", "Black", None))
        self.comboBox_color_y4.setItemText(5, _translate("MainWindow", "Magenta", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_7), _translate("MainWindow", "Y4", None))
        self.label_27.setText(_translate("MainWindow", " Y5:", None))
        self.comboBox_color_y5.setItemText(0, _translate("MainWindow", "Blue", None))
        self.comboBox_color_y5.setItemText(1, _translate("MainWindow", "Green", None))
        self.comboBox_color_y5.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox_color_y5.setItemText(3, _translate("MainWindow", "Yellow", None))
        self.comboBox_color_y5.setItemText(4, _translate("MainWindow", "Black", None))
        self.comboBox_color_y5.setItemText(5, _translate("MainWindow", "Magenta", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_8), _translate("MainWindow", "Y5", None))
        self.label_28.setText(_translate("MainWindow", " Y6:", None))
        self.comboBox_color_y6.setItemText(0, _translate("MainWindow", "Blue", None))
        self.comboBox_color_y6.setItemText(1, _translate("MainWindow", "Green", None))
        self.comboBox_color_y6.setItemText(2, _translate("MainWindow", "Red", None))
        self.comboBox_color_y6.setItemText(3, _translate("MainWindow", "Yellow", None))
        self.comboBox_color_y6.setItemText(4, _translate("MainWindow", "Black", None))
        self.tabWidget_xy.setTabText(self.tabWidget_xy.indexOf(self.tab_9), _translate("MainWindow", "Y6", None))
        self.groupBox.setTitle(_translate("MainWindow", "Control", None))
        self.pushButton_Next.setText(_translate("MainWindow", ">", None))
        self.pushButton_Plot.setText(_translate("MainWindow", "Plot", None))
        self.pushButton_Previous.setText(_translate("MainWindow", "<", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Condition", None))
        self.label_condition.setText(_translate("MainWindow", "Select folder directory", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("MainWindow", "Labels", None))
        self.pushButton_change_name.setText(_translate("MainWindow", "Update", None))
        self.label_7.setText(_translate("MainWindow", " X-Axis Name:", None))
        self.label_8.setText(_translate("MainWindow", " Y-Axis Name:", None))
        self.label_9.setText(_translate("MainWindow", " Plot Name:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_91), _translate("MainWindow", "Axises", None))
        self.label_21.setText(_translate("MainWindow", "Min-X, Max-X:", None))
        self.label_5.setText(_translate("MainWindow", "Min-Y, Max-Y:", None))
        self.pushButton_return.setText(_translate("MainWindow", "Undo", None))
        self.pushButton_modify.setText(_translate("MainWindow", "Modify", None))
        self.checkBox_logx.setText(_translate("MainWindow", "X-LogScale", None))
        self.checkBox_logy.setText(_translate("MainWindow", "Y-LogScale", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("MainWindow", "Range", None))
        self.label_18.setText(_translate("MainWindow", "Time:", None))
        self.pushButton_find.setText(_translate("MainWindow", "Find", None))
        self.label_19.setText(_translate("MainWindow", "Date & Time:", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("MainWindow", "Date-time", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Regular Plotting", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

