# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Tue Sep 29 21:31:17 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1210, 855)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1188, 813))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.groupBox_file = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_file.setGeometry(QtCore.QRect(20, 20, 391, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_file.setFont(font)
        self.groupBox_file.setObjectName(_fromUtf8("groupBox_file"))
        self.lineEdit_address = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_address.setGeometry(QtCore.QRect(120, 170, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_address.setFont(font)
        self.lineEdit_address.setObjectName(_fromUtf8("lineEdit_address"))
        self.pushButton_browse = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_browse.setEnabled(False)
        self.pushButton_browse.setGeometry(QtCore.QRect(70, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_browse.setFont(font)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.label = QtGui.QLabel(self.groupBox_file)
        self.label.setGeometry(QtCore.QRect(20, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.groupBox_file)
        self.label_4.setGeometry(QtCore.QRect(40, 330, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_condition1 = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_condition1.setGeometry(QtCore.QRect(120, 330, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_condition1.setFont(font)
        self.lineEdit_condition1.setObjectName(_fromUtf8("lineEdit_condition1"))
        self.label_10 = QtGui.QLabel(self.groupBox_file)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_divider = QtGui.QLineEdit(self.groupBox_file)
        self.lineEdit_divider.setGeometry(QtCore.QRect(120, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_divider.setFont(font)
        self.lineEdit_divider.setText(_fromUtf8(""))
        self.lineEdit_divider.setObjectName(_fromUtf8("lineEdit_divider"))
        self.radioButton_qmd = QtGui.QRadioButton(self.groupBox_file)
        self.radioButton_qmd.setGeometry(QtCore.QRect(30, 30, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_qmd.setFont(font)
        self.radioButton_qmd.setChecked(False)
        self.radioButton_qmd.setObjectName(_fromUtf8("radioButton_qmd"))
        self.radioButton_other = QtGui.QRadioButton(self.groupBox_file)
        self.radioButton_other.setGeometry(QtCore.QRect(280, 30, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_other.setFont(font)
        self.radioButton_other.setObjectName(_fromUtf8("radioButton_other"))
        self.radioButton_ppms = QtGui.QRadioButton(self.groupBox_file)
        self.radioButton_ppms.setGeometry(QtCore.QRect(180, 30, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_ppms.setFont(font)
        self.radioButton_ppms.setChecked(False)
        self.radioButton_ppms.setObjectName(_fromUtf8("radioButton_ppms"))
        self.pushButton_show = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_show.setEnabled(False)
        self.pushButton_show.setGeometry(QtCore.QRect(220, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_show.setFont(font)
        self.pushButton_show.setObjectName(_fromUtf8("pushButton_show"))
        self.label_11 = QtGui.QLabel(self.groupBox_file)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(20, 220, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.comboBox_recent = QtGui.QComboBox(self.groupBox_file)
        self.comboBox_recent.setEnabled(False)
        self.comboBox_recent.setGeometry(QtCore.QRect(120, 220, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_recent.setFont(font)
        self.comboBox_recent.setObjectName(_fromUtf8("comboBox_recent"))
        self.pushButton_recent = QtGui.QPushButton(self.groupBox_file)
        self.pushButton_recent.setEnabled(False)
        self.pushButton_recent.setGeometry(QtCore.QRect(160, 270, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_recent.setFont(font)
        self.pushButton_recent.setObjectName(_fromUtf8("pushButton_recent"))
        self.groupBox_plot = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_plot.setEnabled(False)
        self.groupBox_plot.setGeometry(QtCore.QRect(430, 20, 731, 771))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_plot.setFont(font)
        self.groupBox_plot.setObjectName(_fromUtf8("groupBox_plot"))
        self.widget = QtGui.QWidget(self.groupBox_plot)
        self.widget.setGeometry(QtCore.QRect(10, 20, 711, 491))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.mplwidget = MatplotlibWidget(self.widget)
        self.mplwidget.setGeometry(QtCore.QRect(290, 200, 16, 16))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.comboBox_x = QtGui.QComboBox(self.groupBox_plot)
        self.comboBox_x.setGeometry(QtCore.QRect(100, 540, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_x.setFont(font)
        self.comboBox_x.setObjectName(_fromUtf8("comboBox_x"))
        self.comboBox_y = QtGui.QComboBox(self.groupBox_plot)
        self.comboBox_y.setGeometry(QtCore.QRect(100, 590, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_y.setFont(font)
        self.comboBox_y.setObjectName(_fromUtf8("comboBox_y"))
        self.pushButton_plot = QtGui.QPushButton(self.groupBox_plot)
        self.pushButton_plot.setEnabled(False)
        self.pushButton_plot.setGeometry(QtCore.QRect(500, 700, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_plot.setFont(font)
        self.pushButton_plot.setObjectName(_fromUtf8("pushButton_plot"))
        self.label_2 = QtGui.QLabel(self.groupBox_plot)
        self.label_2.setGeometry(QtCore.QRect(40, 540, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_plot)
        self.label_3.setGeometry(QtCore.QRect(40, 590, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_plot)
        self.label_5.setGeometry(QtCore.QRect(50, 710, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_condition2 = QtGui.QLineEdit(self.groupBox_plot)
        self.lineEdit_condition2.setGeometry(QtCore.QRect(140, 710, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_condition2.setFont(font)
        self.lineEdit_condition2.setText(_fromUtf8(""))
        self.lineEdit_condition2.setObjectName(_fromUtf8("lineEdit_condition2"))
        self.label_7 = QtGui.QLabel(self.groupBox_plot)
        self.label_7.setGeometry(QtCore.QRect(330, 540, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_x = QtGui.QLineEdit(self.groupBox_plot)
        self.lineEdit_x.setGeometry(QtCore.QRect(470, 540, 221, 31))
        self.lineEdit_x.setObjectName(_fromUtf8("lineEdit_x"))
        self.label_8 = QtGui.QLabel(self.groupBox_plot)
        self.label_8.setGeometry(QtCore.QRect(330, 590, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_y = QtGui.QLineEdit(self.groupBox_plot)
        self.lineEdit_y.setGeometry(QtCore.QRect(470, 590, 221, 31))
        self.lineEdit_y.setObjectName(_fromUtf8("lineEdit_y"))
        self.label_9 = QtGui.QLabel(self.groupBox_plot)
        self.label_9.setGeometry(QtCore.QRect(330, 640, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_name = QtGui.QLineEdit(self.groupBox_plot)
        self.lineEdit_name.setGeometry(QtCore.QRect(430, 640, 261, 31))
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.pushButton_choose2 = QtGui.QPushButton(self.groupBox_plot)
        self.pushButton_choose2.setGeometry(QtCore.QRect(130, 640, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.pushButton_choose2.setFont(font)
        self.pushButton_choose2.setObjectName(_fromUtf8("pushButton_choose2"))
        self.groupBox_labels = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_labels.setEnabled(False)
        self.groupBox_labels.setGeometry(QtCore.QRect(20, 410, 391, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_labels.setFont(font)
        self.groupBox_labels.setObjectName(_fromUtf8("groupBox_labels"))
        self.label_6 = QtGui.QLabel(self.groupBox_labels)
        self.label_6.setGeometry(QtCore.QRect(30, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_labels = QtGui.QTextEdit(self.groupBox_labels)
        self.textEdit_labels.setGeometry(QtCore.QRect(10, 60, 371, 311))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_labels.setFont(font)
        self.textEdit_labels.setObjectName(_fromUtf8("textEdit_labels"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_file.setTitle(_translate("MainWindow", "File", None))
        self.pushButton_browse.setText(_translate("MainWindow", "Browse", None))
        self.label.setText(_translate("MainWindow", "File Address:", None))
        self.label_4.setText(_translate("MainWindow", "Condition:", None))
        self.lineEdit_condition1.setText(_translate("MainWindow", "Please choose your csv file type", None))
        self.label_10.setText(_translate("MainWindow", "Data Divider:", None))
        self.radioButton_qmd.setText(_translate("MainWindow", "QMDLAB File", None))
        self.radioButton_other.setText(_translate("MainWindow", "Other", None))
        self.radioButton_ppms.setText(_translate("MainWindow", "PPMS", None))
        self.pushButton_show.setText(_translate("MainWindow", "Open File", None))
        self.label_11.setText(_translate("MainWindow", "Recent open:", None))
        self.pushButton_recent.setText(_translate("MainWindow", "Open Recent File", None))
        self.groupBox_plot.setTitle(_translate("MainWindow", "Plot", None))
        self.pushButton_plot.setText(_translate("MainWindow", "Change Name", None))
        self.label_2.setText(_translate("MainWindow", " X-Axis", None))
        self.label_3.setText(_translate("MainWindow", " Y-Axis", None))
        self.label_5.setText(_translate("MainWindow", "Condition:", None))
        self.label_7.setText(_translate("MainWindow", " X-Axis Name:", None))
        self.label_8.setText(_translate("MainWindow", " Y-Axis Name:", None))
        self.label_9.setText(_translate("MainWindow", " Plot Name:", None))
        self.pushButton_choose2.setText(_translate("MainWindow", "Plot", None))
        self.groupBox_labels.setTitle(_translate("MainWindow", "Labels", None))
        self.label_6.setText(_translate("MainWindow", "Labels Text Box:", None))

from matplotlibwidget import MatplotlibWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

